//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_AttentionExperiment : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean Confirm
        {
            get
            {
                return SteamVR_Actions.attentionExperiment_Confirm;
            }
        }
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.attentionExperiment_Pose;
            }
        }
        
        public virtual SteamVR_Action_Boolean HeadsetOnHead
        {
            get
            {
                return SteamVR_Actions.attentionExperiment_HeadsetOnHead;
            }
        }
        
        public virtual SteamVR_Action_Vector2 ArrowDirection
        {
            get
            {
                return SteamVR_Actions.attentionExperiment_ArrowDirection;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.attentionExperiment_Haptic;
            }
        }
    }
}
